# gen_answer_source.sh — the linux + darwin arm of the `preBuildScripts` hook
# declared in this example's `.dss-project.json`. See the `$comment` there for
# what the whole chain proves; this file only has to WRITE THE SOURCE.
#
# HOW IT IS INVOKED, and why that shape:
#   * argv is `["/bin/sh", "gen_answer_source.sh"]`. The driver execs argv[0]
#     DIRECTLY — no shell in between, ever (src/core/substrate/process_spawn.hpp)
#     — so this file is an ARGUMENT to /bin/sh and never needs an executable
#     bit. That matters: both corpus runners MIRROR the example directory with
#     `fs::copy_file`, and a mode bit surviving that copy on every host is not
#     something a manifest may depend on.
#   * `/bin/sh` is spelled ABSOLUTELY. POSIX guarantees it on both legs this arm
#     serves (linux and darwin), and an absolute argv[0] removes the question of
#     whose PATH the driver searches. A bare `sh` would also resolve on both,
#     but only by assuming a PATH this file cannot see.
#
# Every path below is RELATIVE, deliberately. The driver spawns this script with
# the BUILD'S working directory as the child's cwd, which is the very directory
# the project manifest's `"generated_*.c"` glob is expanded against. Writing an
# absolute path here would let the two drift apart.

set -eu

out=generated_answer.c

# `printf` (a shell builtin in dash and bash) rather than `cat` + heredoc: this
# script is a BUILD PREREQUISITE, and depending on /bin/cat existing would add a
# second external program to a step whose whole job is to have no surprises.
{
    printf '%s\n' '/* GENERATED by the preBuildScripts hook in .dss-project.json - NOT in git.'
    printf '%s\n' ' * The compile cannot even begin until the pre-build script writes this file'
    printf '%s\n' ' * into the build working directory: the project manifest globs'
    printf '%s\n' ' * "generated_*.c", and a source pattern that matches nothing is a hard'
    printf '%s\n' ' * error (D_FileNotFound), never an empty no-op.'
    printf '%s\n' ' */'
    printf '%s\n' 'int parts[4] = {7, 11, 13, 11};'
    printf '%s\n' ''
    printf '%s\n' 'int sum4(int* p) { return p[0] + p[1] + p[2] + p[3]; }'
    printf '%s\n' ''
    printf '%s\n' 'int main(void) {'
    printf '%s\n' '    return sum4(parts);   /* 7 + 11 + 13 + 11 = 42 */'
    printf '%s\n' '}'
} > "$out"

printf '%s\n' "gen_answer_source.sh: wrote $out in $(pwd)"
