# gen_answer_source.ps1 — the windows arm of the `preBuildScripts` hook declared
# in this example's `.dss-project.json`. Byte-for-byte the same generated source
# as its `gen_answer_source.sh` sibling; only the interpreter differs.
#
# HOW IT IS INVOKED, and why that shape:
#   * argv is
#     ["powershell","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass",
#      "-File","gen_answer_source.ps1"].
#     The driver execs argv[0] DIRECTLY — no shell, no `cmd /c`
#     (src/core/substrate/process_spawn.hpp) — so `-File` is what makes this a
#     script run rather than a REPL.
#   * `powershell` (Windows PowerShell 5.1), NOT `pwsh`. ASSUMPTION, stated so a
#     future reader can check it rather than rediscover it: `powershell.exe`
#     ships with every supported Windows and lives in
#     `%SystemRoot%\System32\WindowsPowerShell\v1.0`, which is on the default
#     PATH; `pwsh` is a separate install present on some CI images and absent on
#     others. The repo's own Windows gate is already a `.ps1`
#     (`build-and-test.ps1`), so PowerShell is a stated prerequisite of this leg
#     and not a new one. If the assumption is ever wrong the corpus runners say
#     so precisely — an unresolvable argv[0] is ledgered
#     `skipped-build-input-missing` naming this program, and is a hard failure
#     under `DSS_STRICT_ARM_VERDICTS=1`.
#   * `-NoProfile` and `-NonInteractive` keep a developer's profile and any
#     prompt out of a build step; `-ExecutionPolicy Bypass` is per-process and
#     needs no privilege.
#
# `-File` and the output path are RELATIVE on purpose: the driver spawns this
# script with the BUILD'S working directory as the child's cwd, which is the
# directory the project manifest's `"generated_*.c"` glob is expanded against.

$ErrorActionPreference = 'Stop'

# `(Get-Location).Path` is PowerShell's own view of the cwd it was started in —
# spelled out rather than passing a bare relative name to Set-Content, because
# PowerShell's provider location and the process working directory are two
# different notions and only one of them is the one the glob will use.
$out = Join-Path (Get-Location).Path 'generated_answer.c'

$body = @'
/* GENERATED by the preBuildScripts hook in .dss-project.json - NOT in git.
 * The compile cannot even begin until the pre-build script writes this file
 * into the build working directory: the project manifest globs
 * "generated_*.c", and a source pattern that matches nothing is a hard
 * error (D_FileNotFound), never an empty no-op.
 */
int parts[4] = {7, 11, 13, 11};

int sum4(int* p) { return p[0] + p[1] + p[2] + p[3]; }

int main(void) {
    return sum4(parts);   /* 7 + 11 + 13 + 11 = 42 */
}
'@

Set-Content -LiteralPath $out -Value $body -Encoding ascii

Write-Output "gen_answer_source.ps1: wrote $out"
