/* EVERY INTEGER WIDTH TO `float`, BIT FOR BIT (D-CSUBSET-INT-TO-F32-CODEGEN, P68 round 12).
 *
 * Generated by the lane's conversion-matrix tooling: each value below is converted by a plain C
 * cast from a `volatile`, and the float's BIT PATTERN is compared with the correctly rounded
 * value computed in exact arithmetic (round to nearest, ties to even, ONE rounding). Check k
 * returns k. Checks 24, 25, 30, 31 are the values a conversion through `double` rounds TWICE and lands on
 * a different float, so a detour through F64 fails them. */
#include <stdint.h>
#include <string.h>

static uint32_t bits_of(float f) { uint32_t u; memcpy(&u, &f, sizeof u); return u; }

int main(void) {
    { volatile signed char x = (-127 - 1); if (bits_of((float)x) != 0xc3000000U) return 1; }
    { volatile signed char x = -1; if (bits_of((float)x) != 0xbf800000U) return 2; }
    { volatile signed char x = 0; if (bits_of((float)x) != 0x00000000U) return 3; }
    { volatile signed char x = 127; if (bits_of((float)x) != 0x42fe0000U) return 4; }
    { volatile unsigned char x = 0U; if (bits_of((float)x) != 0x00000000U) return 5; }
    { volatile unsigned char x = 128U; if (bits_of((float)x) != 0x43000000U) return 6; }
    { volatile unsigned char x = 255U; if (bits_of((float)x) != 0x437f0000U) return 7; }
    { volatile short x = (-32767 - 1); if (bits_of((float)x) != 0xc7000000U) return 8; }
    { volatile short x = -1; if (bits_of((float)x) != 0xbf800000U) return 9; }
    { volatile short x = 32767; if (bits_of((float)x) != 0x46fffe00U) return 10; }
    { volatile unsigned short x = 32768U; if (bits_of((float)x) != 0x47000000U) return 11; }
    { volatile unsigned short x = 65535U; if (bits_of((float)x) != 0x477fff00U) return 12; }
    { volatile int x = (-2147483647 - 1); if (bits_of((float)x) != 0xcf000000U) return 13; }
    { volatile int x = 2147483647; if (bits_of((float)x) != 0x4f000000U) return 14; }
    { volatile int x = 16777217; if (bits_of((float)x) != 0x4b800000U) return 15; }
    { volatile int x = 16777219; if (bits_of((float)x) != 0x4b800002U) return 16; }
    { volatile int x = -16777217; if (bits_of((float)x) != 0xcb800000U) return 17; }
    { volatile unsigned x = 2147483648U; if (bits_of((float)x) != 0x4f000000U) return 18; }
    { volatile unsigned x = 4294967295U; if (bits_of((float)x) != 0x4f800000U) return 19; }
    { volatile unsigned x = 16777217U; if (bits_of((float)x) != 0x4b800000U) return 20; }
    { volatile unsigned x = 4294967040U; if (bits_of((float)x) != 0x4f7fffffU) return 21; }
    { volatile long long x = (-9223372036854775807LL - 1); if (bits_of((float)x) != 0xdf000000U) return 22; }
    { volatile long long x = 9223372036854775807LL; if (bits_of((float)x) != 0x5f000000U) return 23; }
    { volatile long long x = 1152921573326323713LL; if (bits_of((float)x) != 0x5d800001U) return 24; }
    { volatile long long x = -1152921573326323713LL; if (bits_of((float)x) != 0xdd800001U) return 25; }
    { volatile long long x = 9007199254740993LL; if (bits_of((float)x) != 0x5a000000U) return 26; }
    { volatile long long x = 9007199254740995LL; if (bits_of((float)x) != 0x5a000000U) return 27; }
    { volatile unsigned long long x = 18446744073709551615ULL; if (bits_of((float)x) != 0x5f800000U) return 28; }
    { volatile unsigned long long x = 9223372036854775808ULL; if (bits_of((float)x) != 0x5f000000U) return 29; }
    { volatile unsigned long long x = 1152921573326323713ULL; if (bits_of((float)x) != 0x5d800001U) return 30; }
    { volatile unsigned long long x = 9223372586610589697ULL; if (bits_of((float)x) != 0x5f000001U) return 31; }
    { volatile unsigned long long x = 9223372036854776833ULL; if (bits_of((float)x) != 0x5f000000U) return 32; }
    { volatile unsigned long long x = 9007199254740993ULL; if (bits_of((float)x) != 0x5a000000U) return 33; }
    return 42;
}
