# ═══ THE HOST COMPILER'S STAMP — the one dependency every precompiled header had and nobody declared ═══
#
# Run at BUILD time (`cmake -P`) by the `dss_host_compiler_stamp` target in the top-level
# CMakeLists, which also documents the wiring. Two modes:
#   stamp (the default) — write `DSS_HCS_OUTPUT`, a header naming the host C++ compiler this build
#                         tree's precompiled headers are built by, but only when that identity CHANGED;
#   check               — the structural pin, run by the ctest entry `build/pch_host_compiler_stamp`.
#
# ── WHY IT EXISTS ─────────────────────────────────────────────────────────────────────────────
# A precompiled header is only valid for the exact compiler that produced it, and nothing told the
# build so. ✔MEASURED 2026-09-23 (lanes cr and ht): Visual Studio updated MSVC IN PLACE — cl.exe,
# c1xx.dll and c2.dll under the SAME `VC/Tools/MSVC/14.51.36231` directory re-dated, `cl` reporting
# 19.51.36260 instead of 19.51.36257. The compiler PATH did not change, so neither CMake nor ninja
# saw anything, and the next build of every MSVC tree configured before the update failed C1853
# ("precompiled header file is from a different version of the compiler") on EVERY consumer of a PCH.
# The only remedy was a fresh configure — a manual step for an event the build can see for itself.
#
# ⇒ This header is appended to `DSS_PCH_HEADERS`, so every PCH includes it, and it is regenerated
#   whenever the compiler BINARY is newer than its last run (`DEPENDS "${CMAKE_CXX_COMPILER}"`).
#   A compiler updated in place re-runs the stamp → the header's CONTENT changes → every PCH is
#   rebuilt → every consumer is rebuilt. No configure, no C1853. What rebuilds the PCH is the
#   header's place in the dependencies the compiler RECORDED for it (ninja's deps log), not the
#   list: ✔MEASURED 2026-09-23 on MinGW g++ and MSVC, a changed stamp under an unchanged list
#   rebuilt the PCH.
# ⚠ It is appended as a QUOTED INCLUDE LITERAL, not a bare path; the top-level CMakeLists says why
#   (a bare path makes CMake backdate every regenerated cmake_pch.hxx) and refuses the bare form.
# ★ WRITTEN ONLY WHEN THE CONTENT CHANGES. A compiler merely re-dated (same bytes) leaves the header
#   untouched, and CMake's Ninja custom commands `restat`, so nothing downstream rebuilds.
# ★ THE IDENTITY IS THE BINARY'S BYTES, plus the version the compiler reports. The bytes decide; the
#   version line is there so a reader can see WHICH compiler a tree's PCHs were built by without
#   decoding a digest. Neither the path nor a timestamp is in it: the header is part of every PCH's
#   input, and a machine-local spelling would cost the cross-run cache hits `dss_pch_reproducible`
#   exists to keep.
# ⓘ The Debug canary builds PCH-free (`CMAKE_DISABLE_PRECOMPILE_HEADERS`): there is no PCH there to
#   invalidate, and the check below says so rather than passing over it.

cmake_minimum_required(VERSION 4.0)

if(NOT DEFINED DSS_HCS_MODE OR DSS_HCS_MODE STREQUAL "")
    set(DSS_HCS_MODE "stamp")
endif()

function(_dss_hcs_require)
    foreach(_v IN LISTS ARGN)
        if(NOT DEFINED ${_v} OR "${${_v}}" STREQUAL "")
            message(FATAL_ERROR "DssHostCompilerStamp (${DSS_HCS_MODE}): ${_v} is required and was not given.")
        endif()
    endforeach()
endfunction()

# ── stamp ─────────────────────────────────────────────────────────────────────────────────────
if(DSS_HCS_MODE STREQUAL "stamp")
    _dss_hcs_require(DSS_HCS_COMPILER DSS_HCS_OUTPUT)
    if(NOT EXISTS "${DSS_HCS_COMPILER}")
        message(FATAL_ERROR "DssHostCompilerStamp: the host compiler '${DSS_HCS_COMPILER}' does not exist, "
            "so the identity every precompiled header is built against cannot be stated. Reconfigure "
            "against the compiler this tree now uses.")
    endif()
    file(SHA256 "${DSS_HCS_COMPILER}" _digest)
    # The version line: MSVC's `cl` prints its banner (on stderr) when run with no argument; every
    # other compiler this project builds with answers `--version`.
    if(DSS_HCS_COMPILER_ID STREQUAL "MSVC")
        set(_args "")
    else()
        set(_args "--version")
    endif()
    execute_process(COMMAND "${DSS_HCS_COMPILER}" ${_args}
        OUTPUT_VARIABLE _out ERROR_VARIABLE _err RESULT_VARIABLE _rc TIMEOUT 60)
    string(REGEX MATCH "[^\r\n]*[0-9]+\\.[0-9]+[^\r\n]*" _banner "${_out}\n${_err}")
    string(STRIP "${_banner}" _banner)
    if(_banner STREQUAL "")
        set(_banner "(no version line; the compiler exited ${_rc})")
    endif()
    string(REPLACE "\\" "\\\\" _banner "${_banner}")
    string(REPLACE "\"" "\\\"" _banner "${_banner}")
    set(_content
"// GENERATED by cmake/DssHostCompilerStamp.cmake -- do not edit, and do not include it yourself.
// The host C++ compiler every precompiled header of this build tree is built by. Every PCH
// includes this file, so a compiler that changes -- even in place, under the same path -- makes
// every PCH, and so every consumer, rebuild instead of failing on a stale PCH.
#pragma once
#define DSS_HOST_COMPILER_STAMP \"sha256:${_digest} ${_banner}\"
")
    set(_old "")
    if(EXISTS "${DSS_HCS_OUTPUT}")
        file(READ "${DSS_HCS_OUTPUT}" _old)
    endif()
    if(NOT _old STREQUAL _content)
        file(WRITE "${DSS_HCS_OUTPUT}" "${_content}")
        message(STATUS "dss: host compiler stamp -> ${_banner}")
    endif()
    return()
endif()

# ── check: the structural pin ─────────────────────────────────────────────────────────────────
# (a) the build graph's stamp edge lists the compiler BINARY as an input — the declared dependency
#     that makes an in-place update re-run it;
# (b) with PCHs on, every PCH's generated header list includes the stamp (and there are PCHs to
#     check); with them off (the Debug canary), there is NO PCH at all, which is checked, not assumed;
# (c) with PCHs on, every target that builds one is ORDERED after the stamp's target, so a fresh
#     tree never compiles a PCH before the header it includes exists.
if(DSS_HCS_MODE STREQUAL "check")
    _dss_hcs_require(DSS_HCS_BUILD_DIR DSS_HCS_COMPILER DSS_HCS_STAMP DSS_HCS_GENERATOR DSS_HCS_TARGET)
    set(_failures "")
    # The comparison form: forward slashes, and case folded on a host whose paths fold.
    function(_dss_hcs_norm out path)
        file(TO_CMAKE_PATH "${path}" _p)
        if(CMAKE_HOST_WIN32)
            string(TOLOWER "${_p}" _p)
        endif()
        set(${out} "${_p}" PARENT_SCOPE)
    endfunction()
    _dss_hcs_norm(_compiler "${DSS_HCS_COMPILER}")
    _dss_hcs_norm(_stamp "${DSS_HCS_STAMP}")
    get_filename_component(_stamp_name "${DSS_HCS_STAMP}" NAME)

    # (a)
    if(DSS_HCS_GENERATOR MATCHES "Ninja")
        set(_graph "${DSS_HCS_BUILD_DIR}/build.ninja")
        file(STRINGS "${_graph}" _edges REGEX "^build [^\n]*${_stamp_name}[^\n]*: CUSTOM_COMMAND ")
    elseif(DSS_HCS_GENERATOR MATCHES "Makefiles")
        file(GLOB_RECURSE _graph "${DSS_HCS_BUILD_DIR}/CMakeFiles/${DSS_HCS_TARGET}.dir/build.make")
        set(_edges "")
        if(_graph)
            file(STRINGS "${_graph}" _edges REGEX "${_stamp_name}: ")
        endif()
    else()
        message(FATAL_ERROR "DssHostCompilerStamp check: no structural check exists for the generator "
            "'${DSS_HCS_GENERATOR}' -- extend this file rather than let the pin pass unexamined.")
    endif()
    list(LENGTH _edges _nedges)
    set(_edge_ok FALSE)
    foreach(_e IN LISTS _edges)
        # Undo the generator's escapes (ninja: `$ ` `$:` `$$`; make: `\ `) before comparing.
        string(REPLACE "$ " " " _e "${_e}")
        string(REPLACE "$:" ":" _e "${_e}")
        string(REPLACE "$$" "$" _e "${_e}")
        string(REPLACE "\\ " " " _e "${_e}")
        _dss_hcs_norm(_e "${_e}")
        string(FIND "${_e}" "${_compiler}" _at)
        if(NOT _at EQUAL -1)
            set(_edge_ok TRUE)
        endif()
    endforeach()
    if(_nedges EQUAL 0)
        list(APPEND _failures "(a) no edge producing ${_stamp_name} was found in ${_graph}")
    elseif(NOT _edge_ok)
        list(APPEND _failures "(a) the edge producing ${_stamp_name} does not list the compiler binary "
            "${DSS_HCS_COMPILER} as an input: an in-place compiler update would not re-run it")
    else()
        message(STATUS "(a) ok: the stamp edge lists the compiler binary ${DSS_HCS_COMPILER} as an input")
    endif()

    # (b)
    file(GLOB_RECURSE _pchs "${DSS_HCS_BUILD_DIR}/cmake_pch.hxx")
    list(FILTER _pchs EXCLUDE REGEX "/_deps/")
    list(LENGTH _pchs _npch)
    if(DSS_HCS_PCH_DISABLED)
        if(_npch GREATER 0)
            list(APPEND _failures "(b) precompiled headers are DISABLED in this tree, yet ${_npch} "
                "cmake_pch.hxx exist -- a PCH the configuration does not know about")
        else()
            message(STATUS "(b) ok: PCHs are disabled in this tree (the Debug canary) and none exists, "
                "so none can outlive its compiler")
        endif()
    else()
        # ✔MEASURED 2026-09-23: 14 on the MSVC Release tree (13 object libraries + the test producer).
        # A floor, so a header list that silently stopped being generated cannot pass as "all include it".
        set(_floor 10)
        if(_npch LESS _floor)
            list(APPEND _failures "(b) only ${_npch} cmake_pch.hxx found under ${DSS_HCS_BUILD_DIR} (floor ${_floor}) "
                "-- the scan collapsed, or the PCH producers did; fix that, do not lower the floor")
        endif()
        set(_missing "")
        foreach(_h IN LISTS _pchs)
            file(READ "${_h}" _text)
            _dss_hcs_norm(_text "${_text}")
            string(FIND "${_text}" "${_stamp}" _at)
            if(_at EQUAL -1)
                list(APPEND _missing "${_h}")
            endif()
        endforeach()
        if(_missing)
            list(LENGTH _missing _nmissing)
            list(JOIN _missing "\n    " _missing_text)
            list(APPEND _failures "(b) ${_nmissing} of ${_npch} PCH header lists do not include the stamp:\n    ${_missing_text}")
        elseif(_npch GREATER_EQUAL _floor)
            message(STATUS "(b) ok: all ${_npch} PCH header lists include ${DSS_HCS_STAMP}")
        endif()

        # (c) The target a PCH belongs to is the `<target>.dir` its cmake_pch.hxx sits in. Ninja
        #     states the ordering as that target's order-only phony edge; the Makefiles generators,
        #     as a `<target>.dir/all` rule on the stamp target's.
        if(DSS_HCS_GENERATOR MATCHES "Ninja")
            file(STRINGS "${DSS_HCS_BUILD_DIR}/build.ninja" _order REGEX "^build cmake_object_order_depends_target_")
        else()
            file(STRINGS "${DSS_HCS_BUILD_DIR}/CMakeFiles/Makefile2" _order REGEX "\\.dir/all: ")
        endif()
        set(_unordered "")
        foreach(_h IN LISTS _pchs)
            if(NOT _h MATCHES "/CMakeFiles/([^/]+)\\.dir/cmake_pch\\.hxx$")
                list(APPEND _unordered "${_h} (no `<target>.dir` in its path)")
                continue()
            endif()
            set(_tgt "${CMAKE_MATCH_1}")
            set(_ok FALSE)
            if(DSS_HCS_GENERATOR MATCHES "Ninja")
                set(_prefix "build cmake_object_order_depends_target_${_tgt}: phony")
                string(LENGTH "${_prefix}" _plen)
                foreach(_l IN LISTS _order)
                    string(SUBSTRING "${_l}" 0 ${_plen} _head)
                    if(_head STREQUAL _prefix)
                        string(FIND "${_l}" "||" _bar)
                        if(NOT _bar EQUAL -1)
                            math(EXPR _bar "${_bar} + 2")
                            string(SUBSTRING "${_l}" ${_bar} -1 _oo)
                            string(FIND " ${_oo} " " ${DSS_HCS_TARGET} " _at)
                            if(NOT _at EQUAL -1)
                                set(_ok TRUE)
                            endif()
                        endif()
                        break()
                    endif()
                endforeach()
            else()
                # The rule is the whole line for a target of the top directory, and its tail after
                # a `<directory>/` for any other.
                set(_rule "CMakeFiles/${_tgt}.dir/all: CMakeFiles/${DSS_HCS_TARGET}.dir/all")
                string(LENGTH "/${_rule}" _rlen)
                foreach(_l IN LISTS _order)
                    string(STRIP "${_l}" _l)
                    string(LENGTH "${_l}" _llen)
                    set(_tail "")
                    if(_llen GREATER _rlen)
                        math(EXPR _from "${_llen} - ${_rlen}")
                        string(SUBSTRING "${_l}" ${_from} -1 _tail)
                    endif()
                    if(_l STREQUAL _rule OR _tail STREQUAL "/${_rule}")
                        set(_ok TRUE)
                        break()
                    endif()
                endforeach()
            endif()
            if(NOT _ok)
                list(APPEND _unordered "${_tgt}")
            endif()
        endforeach()
        if(_unordered)
            list(LENGTH _unordered _nunordered)
            list(JOIN _unordered ", " _unordered_text)
            list(APPEND _failures "(c) ${_nunordered} of ${_npch} PCH targets are not ordered after "
                "${DSS_HCS_TARGET}, so a fresh build may compile their PCH before the stamp exists: ${_unordered_text}")
        elseif(_npch GREATER_EQUAL _floor)
            message(STATUS "(c) ok: all ${_npch} PCH targets are ordered after ${DSS_HCS_TARGET}")
        endif()
    endif()

    if(_failures)
        list(JOIN _failures "\n  " _text)
        message(FATAL_ERROR "build/pch_host_compiler_stamp: FAILED\n  ${_text}")
    endif()
    message(STATUS "build/pch_host_compiler_stamp: OK")
    return()
endif()

message(FATAL_ERROR "DssHostCompilerStamp: unknown DSS_HCS_MODE '${DSS_HCS_MODE}' (stamp or check).")
